dev_dev/urls.py
# from django.urls import path,include
# from .import views
# urlpatterns = [
#     path('home', views.home,name='home'),
#     path('', views.intro),
# ]

dev_point/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path,include
from dev_dev import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('custom_user_model.urls')),
    path('accounts/',include('allauth.urls')),
    # path('modal',views.modal),
    path('',views.intro),
    path('home',views.home,name='home'),
    path('ask',views.ask_question_view),
    path('question_view',views.question_view),
    path('detail_url/<int:pk>',views.detail_url_view),
    path('answer',views.answer_question_view),
    path('like',views.like),
    path('answer_list',views.answer_list),
    path('comment',views.comment_view),
    path('like_count',views.like_count),
    path('comment_list_view',views.question_comment_list),
    path('email',views.pacchaiamman),
]
# +static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
# path('answer_like',views.answer_like),
# path('ckeditor',include('ckeditor_uploader.urls')),

dev_dev/models.py
from django.db import models
from django.utils import timezone
from custom_user_model.models import Custom_user
from dev_point import settings
from ckeditor_uploader.fields import RichTextUploadingField
from ckeditor.fields import RichTextField

class ask_question(models.Model):
    question_title = models.TextField(max_length='10000',blank=True,null=True)
    question       = models.TextField(max_length='100000')
    user           = models.ForeignKey(settings.AUTH_USER_MODEL,null=True,blank=True,on_delete=models.CASCADE)
    view           = models.IntegerField(default=0,null=True,blank=True)
    create         = models.DateTimeField(auto_now=True)
    like           = models.ManyToManyField(Custom_user,related_name='like',blank=True)
    def __str__(self):
        return self.question_title
    def like_add(self):
        return self.like.count()
class answer_question(models.Model):
    # id_answer = models.ForeignKey(ask_question,related_name="id_answer",default=True,null=False,blank=True,on_delete=models.CASCADE)
    answer          = models.TextField(max_length='10000')
    create          = models.DateTimeField(auto_now=True)
    user_answer     = models.ForeignKey(settings.AUTH_USER_MODEL,null=True,blank=True,on_delete=models.CASCADE)
    question        = models.ForeignKey(ask_question,null=True,blank=True,on_delete=models.CASCADE)
    answer_like     = models.ManyToManyField(Custom_user,related_name='answer_like',blank=True)
    def __str__(self):
        return self.answer
# class like_add(models.Model):
#     user_liked = models.ForeignKey(settings.AUTH_USER_MODEL,null=True,blank=True,on_delete=models.CASCADE)
#     question = models.ForeignKey(ask_question,null=True,blank=True, on_delete = models.CASCADE)
#     val = models.BooleanField(default=False)
# question        = RichTextUploadingField()
# answer         = models.ManyToManyField(answer_question,null=True,blank=True)
class comment_model(models.Model):
    comment     = models.TextField(max_length='9000')
    create      = models.DateTimeField(auto_now=True)
    question        = models.ForeignKey(ask_question,null=True,blank=True,on_delete=models.CASCADE)
    user_answer = models.ForeignKey(settings.AUTH_USER_MODEL,null=True,blank=True,on_delete=models.CASCADE)
    answer      = models.ForeignKey(answer_question,null=True,blank=True,on_delete=models.CASCADE)

# answer = RichTextUploadingField()

templates/html/detail_view.html
{% extends 'html/index.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/detail_view.css' %}">
<!-- <link rel="stylesheet" href="{% static 'css/nav.css' %}"> -->
<script src="{% static 'js/detail.js' %}" type="text/javascript"></script>
<div class="nav_bar_detail">
  {% include 'html/navbar.html' %}
</div>
<div class="content">
  {% include 'html/modal.html' %}
</div>
<section class="container_detail">
  {% for data_detail in data %}
  <section>
  <div class="question_answer">
      <h1 class="question_title_detail">{{ data_detail.question_title }}</h1>
      <div class="user_align">
        <p class="question_user">{{ data_detail.user__username }}</p>
        <p class="detail_create">created : {{ data_detail.create }}</p>
      </div>
      <h1 class="detail_question">{{ data_detail.question }}</h1>
    <div class="question_footer">
      <p class="view_count"><span>views : </span>{{ data_detail.view }}</p>
      <div class="like_btton_count">
        <p class="ll">
        {{ count_like }}
        </p>
      </div>
      {% include 'html/like_unlike_button.html' %}
      <button type="button" class="comment comment_btn" name="button">comment</button>

      </div>
    <section class="comment_section comment_none">
      <form class="" action="index.html" method="post">
        <input class="input_qut" type="text" name="comment" value="">
        <div class="comment_bt">
        <button  type="button" button-id="{{ data_detail.id }}" class="comment_ok" name="button">comment</button>
        <button  type="button" button-id="{{ data_detail.id }}" class="comment_close" name="button">close</button>
        </div>
      </form>
    </section>
  </div>
</section>

<section class="question_commt">
  <h2>comments :</h2>
  <div class="comment_list">
  </div>
</section>
{% endfor %}
</section>

<section>
  <div class="answer_list">
  </div>
</section>
<section class="answer_question">
  {% for data_detail in data %}
  <form class="answer_question_field" method="post">
    <input class="data_detail_id" type="hidden"  id_answer='{{ data_detail.id }}' name="" value='{{ data_detail.id }}'>
    <!-- {{ form_answer.media }} -->
    {{ form_answer.answer }}
    <button type="button"  id_question='{{ data_detail.id }}' class="answer_button_detail" name="button">answer</button>
  </form>
  {% endfor %}
  <div class="answer_get">

  </div>
</section>
{% endblock %}

templates/html/detail_view0.html
{% extends 'html/index.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/detail_view.css' %}">
<link rel="stylesheet" href="{% static 'css/nav.css' %}">
<script src="{% static 'js/detail.js' %}" type="text/javascript"></script>
{% include 'html/navbar.html' %}
<div class="content">
  {% include 'html/modal.html' %}
</div>
<section class="container_detail">
  {% for data_detail in data %}
  <section>
  <div class="question_answer">
      <h1 class="question_title_detail">{{ data_detail.question_title }}</h1>
      <div class="user_align">
        <p class="question_user">{{ data_detail.user__username }}</p>
        <p class="detail_create">created : {{ data_detail.create }}</p>
      </div>
      <h1 class="detail_question">{{ data_detail.question }}</h1>
    <div class="question_footer">
      <p class="view_count"><span>views : </span>{{ data_detail.view }}</p>
      <div class="like_btton_count">
        {{ count_like }}
      </div>
      {% include 'html/like_unlike_button.html' %}
      <button type="button" class="comment comment_btn" name="button">comment</button>
        <!-- <a class=star href="like">
        </a> -->

      </div>
    <section class="comment_section comment_none">
      <form class="" action="index.html" method="post">
        <input class="input_qut" type="text" name="comment" value="">
        <div class="comment_bt">
        <button  type="button" button-id="{{ data_detail.id }}" class="pacchaiamman" name="button">comment</button>
        <button  type="button" button-id="{{ data_detail.id }}" class="pacchaiamman_close" name="button">close</button>
        </div>
      </form>
    </section>
  </div>
</section>
<!-- <div id="comment_questio" class="commentcomment">
  <form class="pacchaiamman_manathieswaran" action="index.html"method="post">
    <input class="input_answer" type="text" name="comment" value="">
    <button  type="button" button-id="{{ data_detail.id }}" class="pacchaiamman" name="button">comment</button>
  </form>
</div> -->

<section class="question_commt">
  <h2>comments :</h2>
  <div class="comment_list">
  </div>
</section>
{% endfor %}
</section>

<section>
  <div class="answer_list">
  </div>
</section>
<section class="answer_question">
  {% for data_detail in data %}
  <form class="answer_question_field" method="post">
    <input class="data_detail_id" type="hidden"  id_answer='{{ data_detail.id }}' name="" value='{{ data_detail.id }}'>
    {{ form_answer.media }}
    {{ form_answer.answer }}
    <button type="button"  id_question='{{ data_detail.id }}' class="answer_button_detail" name="button">answer</button>
  </form>
  {% endfor %}
  <div class="answer_get">

  </div>
</section>
{% endblock %}

templates/html/detail_view1.html
{% extends 'html/index.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/detail_view.css' %}">
<link rel="stylesheet" href="{% static 'css/nav.css' %}">
<script src="{% static 'js/detail.js' %}" type="text/javascript"></script>
{% include 'html/navbar.html' %}
<div class="content">
  {% include 'html/modal.html' %}
</div>
<section class="container_detail">
  {% for data_detail in data %}
  <section>
  <div class="question_answer">
      <h1 class="question_title_detail">{{ data_detail.question_title }}</h1>
      <div class="user_align">
        <p class="question_user">{{ data_detail.user__username }}</p>
        <p class="detail_create">created : {{ data_detail.create }}</p>
      </div>
      <h1 class="detail_question">{{ data_detail.question }}</h1>
    <div class="question_footer">
      <p class="view_count"><span>views : </span>{{ data_detail.view }}</p>
      {% include 'html/like_unlike_button.html' %}
      <button type="button" class="comment comment_btn" name="button">comment</button>
        <!-- <a class=star href="like">
        </a> -->

      </div>
    <section class="comment_section comment_none">
      <form class="" action="index.html" method="post">
        <input class="input_qut" type="text" name="comment" value="">
        <div class="comment_bt">
        <button  type="button" button-id="{{ data_detail.id }}" class="pacchaiamman" name="button">comment</button>
        <button  type="button" button-id="{{ data_detail.id }}" class="pacchaiamman_close" name="button">close</button>
        </div>
      </form>
    </section>
  </div>
</section>
<!-- <div id="comment_questio" class="commentcomment">
  <form class="pacchaiamman_manathieswaran" action="index.html"method="post">
    <input class="input_answer" type="text" name="comment" value="">
    <button  type="button" button-id="{{ data_detail.id }}" class="pacchaiamman" name="button">comment</button>
  </form>
</div> -->

<section class="question_commt">
  <div class="comment_list">
  </div>
</section>
{% endfor %}
</section>

<section>
  <div class="answer_list">
  </div>
</section>
<section class="answer_question">
  {% for data_detail in data %}
  <form class="answer_question_field" method="post">
    <input class="data_detail_id" type="hidden"  id_answer='{{ data_detail.id }}' name="" value='{{ data_detail.id }}'>
    {{ form_answer.media }}
    {{ form_answer.answer }}
    <button type="button"  id_question='{{ data_detail.id }}' class="answer_button_detail" name="button">answer</button>
  </form>
  {% endfor %}
  <div class="answer_get">

  </div>
</section>
{% endblock %}

templates/html/form.html
{% extends 'html/intro.html' %}
{% block content %}
<form method='POST'>
  {% csrf_token %}
  {{ form.email }}
  {{ form.username }}
  {{ form.password1 }}
  {{ form.password2 }}
  <button type="submit" id="save_signup" class="btn save_signup btn-primary">Submit</button>
</form>
{% endblock %}

templates/html/home.html
{% extends 'html/index.html' %}
{% load static %}
{% load socialaccount %}
{% block content %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Anton|Poppins:300 &display=swap" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/gsap@3.0.4/dist/gsap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/1.14.2/TimelineMax.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/1.14.2/TweenMax.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Anton|Poppins:300 &display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/nav.css' %}">
    <script src="{% static 'js/modal.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <style media="screen">
    html body{
      background: #D3D3D3;
    }
    </style>
    <div class="nav_bar_home">
      {% include 'html/navbar.html' %}
    </div>
<section class="home_cont">
  <!-- <div class="hr_vertical"> -->
  <div class="container question_cont">
    <div class="question" id="question_question">
    </div>
    <div class="question_right" id="question_question">
    </div>

  </div>
<!-- </div> -->
{% include 'html/modal.html' %}
</section>
<script type="text/javascript" src="{% static 'js/home.js' %}"></script>
<script type="text/javascript">
    // $(document).ready(function(){
        function ask_question_dev_point(qt,q){
          console.log(qt)
          console.log('question')
          $.ajax({
            type:'POST',
            url:'/ask',
            data: {'question_title':qt,'question':q,},
            success : function(data){
              if (data.success){
                alert("form created")
                question_list();
              }

            }
          });
        }
        $(document).on('click','.savequestion',function(){
          console.log('questtion clicked')
          var question_title  = $("#id_question_title").val();
          var question        = $("#id_question").val();
            console.log(question)
          ask_question_dev_point(question_title,question);
      });
        function question_list(){
        $.ajax({
          type:'POST',
          url:'question_view',
          success : function(data){
            console.log('list')
            var alt = 2
            $.each(data.question,function (key,val){
              if (alt % 2==0){
                console.log(alt)
                $('.question').append('<div class="question_cont_left"  detail-id="'+val.id+'" id="question_left_left"><div class="cont"><div class="question_cont_title"><a class="detail_id_left" href="/detail_url/'+val.id+'" detail-id="'+val.id+'">'+val.question_title+'</a></div><div class="question_cont_asker"></div><input type="hidden" class="detail_input"></input></div><div class="question-footer-left"><p1 class="create_left">'+val.create__date+'</p1><p class="asker">'+val.user__username+'</p></div></div>');

              }else{
                console.log(alt)
                $('.question').append('<div class="question_dummy_right question_cont_right"><div class="cont"><div class="question_cont_title"><a class="detail_id" href="/detail_url/'+val.id+'" detail-id="'+val.id+'">'+val.question_title+'</a></div><input type="hidden" class="detail_input"></input></div><div class="question-footer"><p class="asker_right">'+val.user__username+'</p><p class="create_right">'+val.create__date+'</p></div></div>');

              }
              ++alt
          });
          }
        });
      }
      question_list();
    //0
    $(document).ready(function(){
      let home_nav = document.querySelector('.home-nav')
      // $(window).on('scroll',function(){
      //   var scroll = $(window).scrollTop();
      //   if($(this).scrollTop()>100){
      //     console.log('scroll');
      //     $('.home-nav').addClass('home_nav_onscroll');
      //   }else{
      //     $('.home-nav').removeClass('home_nav_onscroll');
      //   }
      // });
        var tl = new TimelineMax({})

        $(document).on('mouseenter','.question_cont_right',function(){
          console.log('hover in');
          $('.question_cont_right').addClass('question_over');
          $(this).removeClass('question_over');
          $(this).addClass('question_right_hover');
          $('.question_cont_left').addClass('question_left_right_hover');
          $('.question-footer').addClass('question_footer_hover');
          $('.create_right').addClass('create_right_hover');
          $('.detail_id').addClass('detail_id_hover');
        });
        $(document).on('mouseleave','.question_cont_right',function(){
          console.log('hover right');
          $('.question_cont_right').removeClass('question_over');
          $(this).removeClass('question_right_hover');
          $('.question_cont_left').removeClass('question_left_right_hover');
          $('.question-footer').removeClass('question_footer_hover');
          $('.create_right').removeClass('create_right_hover');
          $('.detail_id').removeClass('detail_id_hover');
        });

        $(document).on('mouseenter','.question_cont_left',function(){
          console.log('hover in');
          $('.question_cont_left').addClass('question_over');
          $(this).removeClass('question_over');
          $(this).addClass('question_body_left_hover');
          $('.question_cont_right').addClass('question_body_left_right_hover');
          $('.question-footer-left').addClass('question_footer_left_hover')
          $('.asker').addClass('asker_hover');

        });
        $(document).on('mouseleave','.question_cont_left',function(){
          console.log('hover left');
          $('.question_cont_left').removeClass('question_over');
          $(this).removeClass('question_body_left_hover');
          $('.question_cont_right').removeClass('question_body_left_right_hover');
          $('.question-footer-left').removeClass('question_footer_left_hover')
          $('.asker').removeClass('asker_hover');
        });

  });


</script>
{% endblock %}

templates/html/home0.html
{% extends 'html/index.html' %}
{% load static %}
{% block content %}
<script src="https://cdn.jsdelivr.net/npm/gsap@3.0.4/dist/gsap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/1.14.2/TimelineMax.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/1.14.2/TweenMax.min.js"></script>
<link href="https://fonts.googleapis.com/css?family=Anton|Poppins:300 &display=swap" rel="stylesheet">
<!-- <script type="text/javascript" src="{% static 'js/navbar.js' %}"></script> -->
<link rel="stylesheet" href="{% static 'css/home.css' %}">
{% include 'html/navbar.html' %}
<div class="test">
  <h1>pacchaiamman</h1>
</div>
<section class="home_cont">
  <div class="hr_vertical">
  <div class="container question_cont">
    <div class="question" id="question_question">
    </div>
  </div>
</div>

<script type="text/javascript" src="{% static 'js/home.js' %}"></script>
</section>

<div class="content">
  {% include 'html/modal.html' %}
</div>
{% endblock %}

templates/html/index.html
<!DOCTYPE html>
{% load static %}

<html lang="en" dir="ltr">

  <head>
    <meta charset="utf-8">
    <title>data tabel</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="{% static 'css/nav.css' %}">

    <style media="screen">
    .container{
      /* background: lightgreen; */
      padding: 20px;
    }
    html body{
      /* background: #dfcdc3; */
    }

    .question_body_left: hover{
      font-size: 10vh;
    }
    .test{
    }.div_div{
      background: green;
    }
    .card-body{
      background: green;
      padding-top:200px;
      border: 10px solid lightgreen;
    }
    .hide{
      display: hidden;
    }
    .like_button{
      /* background: green; */
    }
    .Unlike_button{
      /* display: none; */
    }
    .modal-content{
    }
    #id_question_title{
    width:100%;
    height:30vh;
    border:2px solid black;
    font-family: Poppins;
    }
    #ask_question_form{
    }
    #id_question{
    width:100%;
    height:38vh;
    border:2px solid black;
    font-family: Poppins;
    }
    </style>
  </head>

  <body class="back">
    {% block content %}
    {% endblock %}

  </body>
<script type="text/javascript">
$(document).ready(function(){
// $('.btnpacchaiamman').click(function(){
  // $('.comment_section').addClass('comment_section_none');

// });
  $('.btn').click(function(){
    console.log('btn');
  });
});

// $('textarea.editor').ckeditor()
  </script>
</html>

templates/html/intro_svg.html
<!-- {% include 'html/navbar.html' %}
<div class="container question_cont">
  <div class="question">
  </div>
</div> -->

templates/html/li.html
{% if is_liked == False %}
  <p>{{ like_count }}</p>
  <button type="button" class="like_button" like-id='{{ data_detail.id }}' name="button">like</button>
{% else %}
  <p>{{ like_count }}</p>
  <button type="button" class="like_button" like-id='{{ data_detail.id }}' name="button">Unlike</button>
{% endif %}

templates/html/like_unlike_button.html
{% if is_liked == True %}
  <!-- <p class="like_button_count">{{ like.count }}</p> -->
  <button type="button" class="like_button" like-id='{{ data_detail.id }}' name="button">Unlike</button>
{% else %}
  <!-- <p class="like_button_count">{{ like.count }}</p> -->
  <button type="button" class="like_button" like-id='{{ data_detail.id }}' name="button">like</button>
{% endif %}

templates/html/modal.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/modal.css' %}">
<div class="modal custom fade" id="question_model_open">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content  custom-content">
      <div class="custom-header">
        <h5 class="modal-title custom-title" id="exampleModalLongTitle">Ask_your_question</h5>
      </div>
      <form method="POST" enctype="multipart/form-datas" id = "ask_question_form">
        <div class="modal-body custom-body">
          {{ form_ans.media}}
          {{ form_ans.question_title }}
          {{ form_ans.question }}
        </div>
        <div class="custom-footer">
          <button type="button" class="custom_close" data-dismiss="modal">Close</button>
          <button type="button" class="savequestion">Save changes</button>
        </div>
      </form>
    </div>
  </div>
</div>

<div class="modal login_modal custom fade" id="login_model_open">
  <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
    <div class="modal-content custom_content_login">
      <form method='POST'>
        <div class="login_close">
      <div class="custom-header custom_login_title">
        <h5 class="modal-title login_title" id="exampleModalLongTitle">Login<br>Here</h5>
      </div>
      <div class="modal-body login custom_login_body">
        {{ form.email }}
        {{ form.password }}
        <a class="forgot_your_password" >Forgot your password</a><a class='register_here' data-toggle="modal" data-dismiss="modal" data-target='#signup_model_open'>Create a new user</a>
      </div>
      <div class="custom-footer-login">
        <button type="button" class="save_login">Login</button>
      </div>
      </div>
      <div class="email_valid">
      <div class="custom-header custom_login">
        <h5 class="modal-title custom-title" id="exampleModalLongTitle">Enter A Valid Email</h5>
      </div>
      <div class="modal-body passowrd custom-body">
        <input type="email" name="" class="email_password" value="">
      </div>
      <div class="custom-footer">
        <button type="button" class="send_email">email</button>
      </div>
    </div>
    <div class="password_otp">
    <div class="custom-header otp custom_login">
    <h5 class="modal-title custom-title" id="exampleModalLongTitle">Password Reset</h5>
    </div>
    <div class="modal-body custom-body">
      <input type="text" class="otp_enter" name="" value="">
      <input type="password" class="passoword_1" name="" value="">
      <input type="password" class="password_2" name="" value="">
    </div>
    <div class="custom-footer">
    <button type="button" class="password_reset">password_reset</button>
    </div>
    </div>
      </form>
    </div>
  </div>
</div>
<!-- <div class="content"> -->
<div class="modal custom fade" id="signup_model_open">
  <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
    <div class="modal-content custom_content_signup">
      <form method='POST'>
      <div class="signup_close">
      <div class="custom-header custom_signup_title">
        <h5 class="modal-title signup_title" id="exampleModalLongTitle">Register<br>Here</h5>
      </div>
        <div class="modal-body signup custom-body">
          {{ user.email }}
          {{ user.username }}
          {{ user.password1 }}
          {{ user.password2 }}
          <a class='got_a' data-dismiss="modal" data-toggle="modal" data-target='#login_model_open'>Alredy have a account LOGIN HERE </a>
        </div>
        <div class="custom-footer">
          <button type="button" class="save_signup">Register</button>
        </div>
        </div>
        </form>
      </div>
    </div>
  </div>

templates/html/navbar.html
{% extends 'html/index.html' %}
{% load static %}
{% block content %}
<link href="https://fonts.googleapis.com/css?family=Anton|Poppins:300 &display=swap" rel="stylesheet">
<script src="{% static 'js/navbar.js' %}"></script>
<link rel="stylesheet" href="{% static 'css/nav.css' %}">
<div class="nav_bar_home">
  <nav class=" home-nav">
    <div class="logo-home dummy_logo" id='triangle-toleft'>
      <img class="dummy-img imgdumy" src="{% static 'img/logo.png' %}" alt="">
    </div>
    <div class="nav-slice_li">
    <div class="home-menu dummy_home_menu">
      <ul class="home-menu-left">
        <li class='Ask_a_question'><button type="button"  class='ask question_model' data-toggle="modal" data-target='#question_model_open' name="button">Ask_a_question</button></li>
        <li class='help_dev'><button type="button" class='ans question_model' name="button">Dev_blog</button></li>
        {% if request.user.is_authenticated %}
          <li class="hamp_log"><button type="button" class="logout question_model" name="button"><a class="logout_link" href="logout">Sign_out</a></button></li>
          <li><button type="button" class="username question_model" name="button">{{ request.user.username }}</button></li>
        {% else %}
          <li><button type="button"  class='question_model' data-toggle="modal" data-target='#login_model_open' name="button">Login</button></li>
        {% endif %}
        <button type="button" class="close" aria-label="Close">
          <span>&times;</span>
        </button>
      </ul>
      {% include 'html/modal.html' %}

      <div class="pacchaiamman line">
        <div class="line_1"></div>
        <h1>menu</h1>
        <div class="line_3"></div>
      </div>
    </div>
  </nav>
</div>
{% endblock %}